<?php

$imagenes = array(
'0'=> array('name'=>'glyphicon-glass', 'descript'=>'Glass','type'=>'0'),
'1'=> array('name'=>'glyphicon-music', 'descript'=>'Music','type'=>'0'),
'2'=> array('name'=>'glyphicon-search', 'descript'=>'Search','type'=>'0'),
'3'=> array('name'=>'glyphicon-envelope', 'descript'=>'Envelope','type'=>'0'),
'4'=> array('name'=>'glyphicon-user', 'descript'=>'User','type'=>'0'),
'5'=> array('name'=>'glyphicon-film', 'descript'=>'Film','type'=>'0'),
'6'=> array('name'=>'glyphicon-th-large', 'descript'=>'Th Large','type'=>'0'),
'7'=> array('name'=>'glyphicon-th', 'descript'=>'Th','type'=>'0'),
'8'=> array('name'=>'glyphicon-th-list', 'descript'=>'Th List','type'=>'0'),
'9'=> array('name'=>'glyphicon-ok', 'descript'=>'Ok','type'=>'0'),
'10'=> array('name'=>'glyphicon-remove', 'descript'=>'Remove','type'=>'0'),
'11'=> array('name'=>'glyphicon-zoom-in', 'descript'=>'Zoom In','type'=>'0'),
'12'=> array('name'=>'glyphicon-zoom-out', 'descript'=>'Zoom Out','type'=>'0'),
'13'=> array('name'=>'glyphicon-off', 'descript'=>'Off','type'=>'0'),
'14'=> array('name'=>'glyphicon-signal', 'descript'=>'Signal','type'=>'0'),
'15'=> array('name'=>'glyphicon-cog', 'descript'=>'Cog','type'=>'0'),
'16'=> array('name'=>'glyphicon-trash', 'descript'=>'Trash','type'=>'0'),
'17'=> array('name'=>'glyphicon-home', 'descript'=>'Home','type'=>'0'),
'18'=> array('name'=>'glyphicon-file', 'descript'=>'File','type'=>'0'),
'19'=> array('name'=>'glyphicon-time', 'descript'=>'Time','type'=>'0'),
'20'=> array('name'=>'glyphicon-download-alt', 'descript'=>'Download Alt','type'=>'0'),
'21'=> array('name'=>'glyphicon-download', 'descript'=>'Download','type'=>'0'),
'22'=> array('name'=>'glyphicon-upload', 'descript'=>'Upload','type'=>'0'),
'23'=> array('name'=>'glyphicon-inbox', 'descript'=>'Inbox','type'=>'0'),
'24'=> array('name'=>'glyphicon-play-circle', 'descript'=>'Play Circle','type'=>'0'),
'25'=> array('name'=>'glyphicon-repeat', 'descript'=>'Repeat','type'=>'0'),
'26'=> array('name'=>'glyphicon-refresh', 'descript'=>'Refresh','type'=>'0'),
'27'=> array('name'=>'glyphicon-list-alt', 'descript'=>'Alt','type'=>'0'),
'28'=> array('name'=>'glyphicon-lock', 'descript'=>'Lock','type'=>'0'),
'29'=> array('name'=>'glyphicon-flag', 'descript'=>'Flag','type'=>'0'),
'30'=> array('name'=>'glyphicon-volume-off', 'descript'=>'Volume Off','type'=>'0'),
'31'=> array('name'=>'glyphicon-volume-down', 'descript'=>'Volume Down','type'=>'0'),
'32'=> array('name'=>'glyphicon-volume-up', 'descript'=>'Volume Up','type'=>'0'),
'33'=> array('name'=>'glyphicon-qrcode', 'descript'=>'Qrcode','type'=>'0'),
'34'=> array('name'=>'glyphicon-barcode', 'descript'=>'Barcode','type'=>'0'),
'35'=> array('name'=>'glyphicon-tag', 'descript'=>'Tag','type'=>'0'),
'36'=> array('name'=>'glyphicon-tags', 'descript'=>'Tags','type'=>'0'),
'37'=> array('name'=>'glyphicon-book', 'descript'=>'Book','type'=>'0'),
'38'=> array('name'=>'glyphicon-bookmark>', 'descript'=>'Bookmark>','type'=>'0'),
'39'=> array('name'=>'glyphicon-print', 'descript'=>'Print','type'=>'0'),
'40'=> array('name'=>'glyphicon-camera>', 'descript'=>'Camera>','type'=>'0'),
'41'=> array('name'=>'glyphicon-font', 'descript'=>'Font','type'=>'0'),
'42'=> array('name'=>'glyphicon-bold', 'descript'=>'Bold','type'=>'0'),
'43'=> array('name'=>'glyphicon-italic', 'descript'=>'Italic','type'=>'0'),
'44'=> array('name'=>'glyphicon-text-height', 'descript'=>'Text Height','type'=>'0'),
'45'=> array('name'=>'glyphicon-text-width', 'descript'=>'Text Width','type'=>'0'),
'46'=> array('name'=>'glyphicon-align-left', 'descript'=>'Align Left','type'=>'0'),
'47'=> array('name'=>'glyphicon-align-center', 'descript'=>'Align Center','type'=>'0'),
'48'=> array('name'=>'glyphicon-align-right', 'descript'=>'Align Right','type'=>'0'),
'49'=> array('name'=>'glyphicon-align-justify', 'descript'=>'Align Justify','type'=>'0'),
'50'=> array('name'=>'glyphicon-list', 'descript'=>'List','type'=>'0'),
'51'=> array('name'=>'glyphicon-indent-left', 'descript'=>'Indent Left','type'=>'0'),
'52'=> array('name'=>'glyphicon-indent-right', 'descript'=>'Indent Right','type'=>'0'),
'53'=> array('name'=>'glyphicon-facetime-video', 'descript'=>'Facetime Video','type'=>'0'),
'54'=> array('name'=>'glyphicon-picture', 'descript'=>'Picture','type'=>'0'),
'55'=> array('name'=>'glyphicon-pencil', 'descript'=>'Pencil','type'=>'0'),
'56'=> array('name'=>'glyphicon-map-marker', 'descript'=>'Map Marker','type'=>'0'),
'57'=> array('name'=>'glyphicon-adjust', 'descript'=>'Adjust','type'=>'0'),
'58'=> array('name'=>'glyphicon-tint', 'descript'=>'Tint','type'=>'0'),
'59'=> array('name'=>'glyphicon-edit', 'descript'=>'Edit','type'=>'0'),
'60'=> array('name'=>'glyphicon-share', 'descript'=>'Share','type'=>'0'),
'61'=> array('name'=>'glyphicon-check', 'descript'=>'Check','type'=>'0'),
'62'=> array('name'=>'glyphicon-move', 'descript'=>'Move','type'=>'0'),
'63'=> array('name'=>'glyphicon-step-backward', 'descript'=>'Step Backward','type'=>'0'),
'64'=> array('name'=>'glyphicon-fast-backward', 'descript'=>'Fast Backward','type'=>'0'),
'65'=> array('name'=>'glyphicon-backward', 'descript'=>'Backward','type'=>'0'),
'66'=> array('name'=>'glyphicon-play', 'descript'=>'Play','type'=>'0'),
'67'=> array('name'=>'glyphicon-pause', 'descript'=>'Pause','type'=>'0'),
'68'=> array('name'=>'glyphicon-stop', 'descript'=>'Stop','type'=>'0'),
'69'=> array('name'=>'glyphicon-forward', 'descript'=>'Forward','type'=>'0'),
'70'=> array('name'=>'glyphicon-fast-forward', 'descript'=>'Fast Forward','type'=>'0'),
'71'=> array('name'=>'glyphicon-step-forward', 'descript'=>'Step Forward','type'=>'0'),
'72'=> array('name'=>'glyphicon-chevron-left', 'descript'=>'Chevron Left','type'=>'0'),
'73'=> array('name'=>'glyphicon-chevron-right', 'descript'=>'Chevron Right','type'=>'0'),
'74'=> array('name'=>'glyphicon-plus-sign', 'descript'=>'Plus Sign','type'=>'0'),
'75'=> array('name'=>'glyphicon-minus-sign', 'descript'=>'Minus Sign','type'=>'0'),
'76'=> array('name'=>'glyphicon-remove-sign', 'descript'=>'Remove Sign','type'=>'0'),
'77'=> array('name'=>'glyphicon-ok-sign', 'descript'=>'Ok Sign','type'=>'0'),
'78'=> array('name'=>'glyphicon-question-sign', 'descript'=>'Question Sign','type'=>'0'),
'79'=> array('name'=>'glyphicon-info-sign', 'descript'=>'Info Sign','type'=>'0'),
'80'=> array('name'=>'glyphicon-screenshot', 'descript'=>'Screenshot','type'=>'0'),
'81'=> array('name'=>'glyphicon-remove-circle', 'descript'=>'Remove Circle','type'=>'0'),
'82'=> array('name'=>'glyphicon-ok-circle', 'descript'=>'Ok Circle','type'=>'0'),
'83'=> array('name'=>'glyphicon-ban-circle', 'descript'=>'Ban Circle','type'=>'0'),
'84'=> array('name'=>'glyphicon-arrow-left', 'descript'=>'Arrow Left','type'=>'0'),
'85'=> array('name'=>'glyphicon-arrow-right', 'descript'=>'Arrow Right','type'=>'0'),
'86'=> array('name'=>'glyphicon-arrow-up', 'descript'=>'Arrow Up','type'=>'0'),
'87'=> array('name'=>'glyphicon-arrow-down', 'descript'=>'Arrow Down','type'=>'0'),
'88'=> array('name'=>'glyphicon-share-alt', 'descript'=>'Share Alt','type'=>'0'),
'89'=> array('name'=>'glyphicon-resize-full', 'descript'=>'Resize Full','type'=>'0'),
'90'=> array('name'=>'glyphicon-resize-small', 'descript'=>'Resize Small','type'=>'0'),
'91'=> array('name'=>'glyphicon-plus', 'descript'=>'Plus','type'=>'0'),
'92'=> array('name'=>'glyphicon-minus', 'descript'=>'Minus','type'=>'0'),
'93'=> array('name'=>'glyphicon-asterisk', 'descript'=>'Asterisk','type'=>'0'),
'94'=> array('name'=>'glyphicon-exclamation-sign', 'descript'=>'Exclamation Sign','type'=>'0'),
'95'=> array('name'=>'glyphicon-gift', 'descript'=>'Gift','type'=>'0'),
'96'=> array('name'=>'glyphicon-leaf', 'descript'=>'Leaf','type'=>'0'),
'97'=> array('name'=>'glyphicon-fire', 'descript'=>'Fire','type'=>'0'),
'98'=> array('name'=>'glyphicon-eye-open', 'descript'=>'Eye Open','type'=>'0'),
'99'=> array('name'=>'glyphicon-eye-close', 'descript'=>'Eye Close','type'=>'0'),
'100'=> array('name'=>'glyphicon-warning-sign', 'descript'=>'Warning Sign','type'=>'0'),
'101'=> array('name'=>'glyphicon-plane', 'descript'=>'Plane','type'=>'0'),
'102'=> array('name'=>'glyphicon-calendar', 'descript'=>'Calendar','type'=>'0'),
'103'=> array('name'=>'glyphicon-random', 'descript'=>'Random','type'=>'0'),
'104'=> array('name'=>'glyphicon-comment', 'descript'=>'Comment','type'=>'0'),
'105'=> array('name'=>'glyphicon-magnet', 'descript'=>'Magnet','type'=>'0'),
'106'=> array('name'=>'glyphicon-chevron-up', 'descript'=>'Chevron Up','type'=>'0'),
'107'=> array('name'=>'glyphicon-chevron-down', 'descript'=>'Chevron Down','type'=>'0'),
'108'=> array('name'=>'glyphicon-retweet', 'descript'=>'Retweet','type'=>'0'),
'109'=> array('name'=>'glyphicon-shopping-cart', 'descript'=>'Shopping Cart','type'=>'0'),
'110'=> array('name'=>'glyphicon-folder-close', 'descript'=>'Folder Close','type'=>'0'),
'111'=> array('name'=>'glyphicon-folder-open', 'descript'=>'Folder Open','type'=>'0'),
'112'=> array('name'=>'glyphicon-resize-vertical', 'descript'=>'Resize Vertical','type'=>'0'),
'113'=> array('name'=>'glyphicon-resize-horizontal', 'descript'=>'Resize Horizontal','type'=>'0'),
'114'=> array('name'=>'glyphicon-hdd', 'descript'=>'Hdd','type'=>'0'),
'115'=> array('name'=>'glyphicon-bullhorn', 'descript'=>'Bullhorn','type'=>'0'),
'116'=> array('name'=>'glyphicon-bell', 'descript'=>'Bell','type'=>'0'),
'117'=> array('name'=>'glyphicon-certificate', 'descript'=>'Certificate','type'=>'0'),
'118'=> array('name'=>'glyphicon-thumbs-up', 'descript'=>'Thumbs Up','type'=>'0'),
'119'=> array('name'=>'glyphicon-thumbs-down', 'descript'=>'Thumbs Down','type'=>'0'),
'120'=> array('name'=>'glyphicon-hand-right', 'descript'=>'Hand Right','type'=>'0'),
'121'=> array('name'=>'glyphicon-hand-left', 'descript'=>'Hand Left','type'=>'0'),
'122'=> array('name'=>'glyphicon-hand-up', 'descript'=>'Hand Up','type'=>'0'),
'123'=> array('name'=>'glyphicon-hand-down', 'descript'=>'Hand Down','type'=>'0'),
'124'=> array('name'=>'glyphicon-circle-arrow-right', 'descript'=>'','type'=>'0'),
'125'=> array('name'=>'glyphicon-circle-arrow-left', 'descript'=>'','type'=>'0'),
'126'=> array('name'=>'glyphicon-circle-arrow-up', 'descript'=>'','type'=>'0'),
'127'=> array('name'=>'glyphicon-circle-arrow-down', 'descript'=>'','type'=>'0'),
'128'=> array('name'=>'glyphicon-globe', 'descript'=>'Globe','type'=>'0'),
'129'=> array('name'=>'glyphicon-wrench', 'descript'=>'Wrench','type'=>'0'),
'130'=> array('name'=>'glyphicon-tasks', 'descript'=>'Tasks','type'=>'0'),
'131'=> array('name'=>'glyphicon-filter', 'descript'=>'Filter','type'=>'0'),
'132'=> array('name'=>'glyphicon-briefcase', 'descript'=>'Briefcase','type'=>'0'),
'133'=> array('name'=>'glyphicon-fullscreen', 'descript'=>'Fullscreen','type'=>'0'),
'134'=> array('name'=>'glyphicon-dashboard', 'descript'=>'Dashboard','type'=>'0'),
'135'=> array('name'=>'glyphicon-paperclipn', 'descript'=>'Paperclipn','type'=>'0'),
'136'=> array('name'=>'glyphicon-heart-empty', 'descript'=>'Heart Empty','type'=>'0'),
'137'=> array('name'=>'glyphicon-link', 'descript'=>'Link','type'=>'0'),
'138'=> array('name'=>'glyphicon-phone', 'descript'=>'Phone','type'=>'0'),
'139'=> array('name'=>'glyphicon-pushpin', 'descript'=>'Pushpin','type'=>'0'),
'140'=> array('name'=>'glyphicon-euro', 'descript'=>'Euro','type'=>'0'),
'141'=> array('name'=>'glyphicon-usd', 'descript'=>'Usd','type'=>'0'),
'142'=> array('name'=>'glyphicon-gbp', 'descript'=>'Gbp','type'=>'0'),
'143'=> array('name'=>'glyphicon-sort', 'descript'=>'Sort','type'=>'0'),
'144'=> array('name'=>'glyphicon-sort-by-alphabet', 'descript'=>'','type'=>'0'),
'145'=> array('name'=>'glyphicon-sort-by-alphabet-alt', 'descript'=>'','type'=>'0'),
'146'=> array('name'=>'glyphicon-sort-by-order', 'descript'=>'','type'=>'0'),
'147'=> array('name'=>'glyphicon-sort-by-order-alt', 'descript'=>'','type'=>'0'),
'148'=> array('name'=>'glyphicon-sort-by-attributes', 'descript'=>'','type'=>'0'),
'149'=> array('name'=>'glyphicon-sort-by-attributes-alt', 'descript'=>'','type'=>'0'),
'150'=> array('name'=>'glyphicon-unchecked', 'descript'=>'Unchecked','type'=>'0'),
'151'=> array('name'=>'glyphicon-expand', 'descript'=>'Expand','type'=>'0'),
'152'=> array('name'=>'glyphicon-collapse-down', 'descript'=>'Collapse Down','type'=>'0'),
'153'=> array('name'=>'glyphicon-collapse-top', 'descript'=>'Collapse Top','type'=>'0'),
'154'=> array('name'=>'glyphicon-log-in', 'descript'=>'Log In','type'=>'0'),
'155'=> array('name'=>'glyphicon-flash', 'descript'=>'Flash','type'=>'0'),
'156'=> array('name'=>'glyphicon-log-out', 'descript'=>'Log Out','type'=>'0'),
'157'=> array('name'=>'glyphicon-new-window', 'descript'=>'New Window','type'=>'0'),
'158'=> array('name'=>'glyphicon-record', 'descript'=>'Record','type'=>'0'),
'159'=> array('name'=>'glyphicon-save', 'descript'=>'Save','type'=>'0'),
'160'=> array('name'=>'glyphicon-open', 'descript'=>'Open','type'=>'0'),
'161'=> array('name'=>'glyphicon-saved', 'descript'=>'Saved','type'=>'0'),
'162'=> array('name'=>'glyphicon-import', 'descript'=>'Import','type'=>'0'),
'163'=> array('name'=>'glyphicon-export', 'descript'=>'Export','type'=>'0'),
'164'=> array('name'=>'glyphicon-send', 'descript'=>'Send','type'=>'0'),
'165'=> array('name'=>'glyphicon-floppy-disk', 'descript'=>'Floppy Disk','type'=>'0'),
'166'=> array('name'=>'glyphicon-floppy-saved', 'descript'=>'Floppy Saved','type'=>'0'),
'167'=> array('name'=>'glyphicon-floppy-remove', 'descript'=>'Floppy Remove','type'=>'0'),
'168'=> array('name'=>'glyphicon-floppy-save', 'descript'=>'Floppy Save','type'=>'0'),
'169'=> array('name'=>'glyphicon-floppy-open', 'descript'=>'Floppy Open','type'=>'0'),
'170'=> array('name'=>'glyphicon-credit-card', 'descript'=>'Credit Card','type'=>'0'),
'171'=> array('name'=>'glyphicon-transfer', 'descript'=>'Transfer','type'=>'0'),
'172'=> array('name'=>'glyphicon-cutlery', 'descript'=>'Cutlery','type'=>'0'),
'173'=> array('name'=>'glyphicon-header', 'descript'=>'Header','type'=>'0'),
'174'=> array('name'=>'glyphicon-compressed', 'descript'=>'Compressed','type'=>'0'),
'175'=> array('name'=>'glyphicon-earphone', 'descript'=>'Earphone','type'=>'0'),
'176'=> array('name'=>'glyphicon-phone-alt', 'descript'=>'Phone Alt','type'=>'0'),
'177'=> array('name'=>'glyphicon-tower', 'descript'=>'Tower','type'=>'0'),
'178'=> array('name'=>'glyphicon-stats', 'descript'=>'Stats','type'=>'0'),
'179'=> array('name'=>'glyphicon-sd-video', 'descript'=>'Sd Video','type'=>'0'),
'180'=> array('name'=>'glyphicon-hd-video', 'descript'=>'Hd Video','type'=>'0'),
'181'=> array('name'=>'glyphicon-subtitles', 'descript'=>'Subtitles','type'=>'0'),
'182'=> array('name'=>'glyphicon-sound-stereo', 'descript'=>'Sound Stereo','type'=>'0'),
'183'=> array('name'=>'glyphicon-sound-dolby', 'descript'=>'Sound Dolby','type'=>'0'),
'184'=> array('name'=>'glyphicon-sound-5-1', 'descript'=>'1','type'=>'0'),
'185'=> array('name'=>'glyphicon-sound-6-1', 'descript'=>'1','type'=>'0'),
'186'=> array('name'=>'glyphicon-sound-7-1', 'descript'=>'1','type'=>'0'),
'187'=> array('name'=>'glyphicon-copyright-mark', 'descript'=>'Copyright Mark','type'=>'0'),
'188'=> array('name'=>'glyphicon-registration-mark', 'descript'=>'Registration Mark','type'=>'0'),
'189'=> array('name'=>'glyphicon-cloud', 'descript'=>'Cloud','type'=>'0'),
'190'=> array('name'=>'glyphicon-cloud-download', 'descript'=>'Cloud Download','type'=>'0'),
'191'=> array('name'=>'glyphicon-cloud-upload', 'descript'=>'Cloud Upload','type'=>'0'),
'192'=> array('name'=>'glyphicon-tree-conifer', 'descript'=>'Tree Conifer','type'=>'0'),
'193'=> array('name'=>'glyphicon-tree-deciduous', 'descript'=>'Tree Deciduous','type'=>'0'),
'194'=> array('name'=>'l-banknote', 'descript'=>'Banknote','type'=>'1'),
'195'=> array('name'=>'l-weather-aquarius', 'descript'=>'Weather Aquarius','type'=>'1'),
'196'=> array('name'=>'l-weather-aries', 'descript'=>'Weather Aries','type'=>'1'),
'197'=> array('name'=>'l-weather-cancer', 'descript'=>'Weather Cancer','type'=>'1'),
'198'=> array('name'=>'l-weather-capricorn', 'descript'=>'Weather Capricorn','type'=>'1'),
'199'=> array('name'=>'l-weather-cloud', 'descript'=>'Weather Cloud','type'=>'1'),
'200'=> array('name'=>'l-weather-cloud-drop', 'descript'=>'Weather Cloud Drop','type'=>'1'),
'201'=> array('name'=>'l-weather-cloud-lightning', 'descript'=>'Weather Cloud Lightning','type'=>'1'),
'202'=> array('name'=>'l-weather-cloud-snowflake', 'descript'=>'Weather Cloud Snowflake','type'=>'1'),
'203'=> array('name'=>'l-weather-downpour-fullmoon', 'descript'=>'Weather Downpour Fullmoon','type'=>'1'),
'204'=> array('name'=>'l-weather-downpour-halfmoon', 'descript'=>'Weather Downpour Halfmoon','type'=>'1'),
'205'=> array('name'=>'l-weather-downpour-sun', 'descript'=>'Weather Downpour Sun','type'=>'1'),
'206'=> array('name'=>'l-weather-drop', 'descript'=>'Weather Drop','type'=>'1'),
'207'=> array('name'=>'l-weather-first-quarter', 'descript'=>'Weather First Quarter','type'=>'1'),
'208'=> array('name'=>'l-weather-fog', 'descript'=>'Weather Fog','type'=>'1'),
'209'=> array('name'=>'l-weather-fog-fullmoon', 'descript'=>'Weather Fog Fullmoon','type'=>'1'),
'210'=> array('name'=>'l-weather-fog-halfmoon', 'descript'=>'Weather Fog Halfmoon','type'=>'1'),
'211'=> array('name'=>'l-weather-fog-sun', 'descript'=>'Weather Fog Sun','type'=>'1'),
'212'=> array('name'=>'l-weather-fullmoon', 'descript'=>'Weather Fullmoon','type'=>'1'),
'213'=> array('name'=>'l-weather-gemini', 'descript'=>'Weather Gemini','type'=>'1'),
'214'=> array('name'=>'l-weather-hail', 'descript'=>'Weather Hail','type'=>'1'),
'215'=> array('name'=>'l-weather-hail-fullmoon', 'descript'=>'Weather Hail Fullmoon','type'=>'1'),
'216'=> array('name'=>'l-weather-hail-halfmoon', 'descript'=>'Weather Hail Halfmoon','type'=>'1'),
'217'=> array('name'=>'l-weather-hail-sun', 'descript'=>'Weather Hail Sun','type'=>'1'),
'218'=> array('name'=>'l-weather-last-quarter', 'descript'=>'Weather Last Quarter','type'=>'1'),
'219'=> array('name'=>'l-weather-leo', 'descript'=>'Weather Leo','type'=>'1'),
'220'=> array('name'=>'l-weather-libra', 'descript'=>'Weather Libra','type'=>'1'),
'221'=> array('name'=>'l-weather-lightning', 'descript'=>'Weather Lightning','type'=>'1'),
'222'=> array('name'=>'l-weather-mistyrain', 'descript'=>'Weather Mistyrain','type'=>'1'),
'223'=> array('name'=>'l-weather-mistyrain-fullmoon', 'descript'=>'Weather Mistyrain Fullmoon','type'=>'1'),
'224'=> array('name'=>'l-weather-mistyrain-halfmoon', 'descript'=>'Weather Mistyrain Halfmoon','type'=>'1'),
'225'=> array('name'=>'l-weather-mistyrain-sun', 'descript'=>'Weather Mistyrain Sun','type'=>'1'),
'226'=> array('name'=>'l-weather-moon', 'descript'=>'Weather Moon','type'=>'1'),
'227'=> array('name'=>'l-weather-moondown-full', 'descript'=>'Weather Moondown Full','type'=>'1'),
'228'=> array('name'=>'l-weather-moondown-half', 'descript'=>'Weather Moondown Half','type'=>'1'),
'229'=> array('name'=>'l-weather-moonset-full', 'descript'=>'Weather Moonset Full','type'=>'1'),
'230'=> array('name'=>'l-weather-moonset-half', 'descript'=>'Weather Moonset Half','type'=>'1'),
'231'=> array('name'=>'l-weather-move2', 'descript'=>'Weather Move2','type'=>'1'),
'232'=> array('name'=>'l-weather-newmoon', 'descript'=>'Weather Newmoon','type'=>'1'),
'233'=> array('name'=>'l-weather-pisces', 'descript'=>'Weather Pisces','type'=>'1'),
'234'=> array('name'=>'l-weather-rain', 'descript'=>'Weather Rain','type'=>'1'),
'235'=> array('name'=>'l-weather-rain-fullmoon', 'descript'=>'Weather Rain Fullmoon','type'=>'1'),
'236'=> array('name'=>'l-weather-rain-halfmoon', 'descript'=>'Weather Rain Halfmoon','type'=>'1'),
'237'=> array('name'=>'l-weather-rain-sun', 'descript'=>'Weather Rain Sun','type'=>'1'),
'238'=> array('name'=>'l-weather-sagittarius', 'descript'=>'Weather Sagittarius','type'=>'1'),
'239'=> array('name'=>'l-weather-scorpio', 'descript'=>'Weather Scorpio','type'=>'1'),
'240'=> array('name'=>'l-weather-snow', 'descript'=>'Weather Snow','type'=>'1'),
'241'=> array('name'=>'l-weather-snow-fullmoon', 'descript'=>'Weather Snow Fullmoon','type'=>'1'),
'242'=> array('name'=>'l-weather-snow-halfmoon', 'descript'=>'Weather Snow Halfmoon','type'=>'1'),
'243'=> array('name'=>'l-weather-snow-sun', 'descript'=>'Weather Snow Sun','type'=>'1'),
'244'=> array('name'=>'l-weather-snowflake', 'descript'=>'Weather Snowflake','type'=>'1'),
'245'=> array('name'=>'l-weather-star', 'descript'=>'Weather Star','type'=>'1'),
'246'=> array('name'=>'l-weather-storm-11', 'descript'=>'Weather Storm 11','type'=>'1'),
'247'=> array('name'=>'l-weather-storm-32', 'descript'=>'Weather Storm 32','type'=>'1'),
'248'=> array('name'=>'l-weather-storm-fullmoon', 'descript'=>'Weather Storm Fullmoon','type'=>'1'),
'249'=> array('name'=>'l-weather-storm-halfmoon', 'descript'=>'Weather Storm Halfmoon','type'=>'1'),
'250'=> array('name'=>'l-weather-storm-sun', 'descript'=>'Weather Storm Sun','type'=>'1'),
'251'=> array('name'=>'l-weather-sun', 'descript'=>'Weather Sun','type'=>'1'),
'252'=> array('name'=>'l-weather-sundown', 'descript'=>'Weather Sundown','type'=>'1'),
'253'=> array('name'=>'l-weather-sunset', 'descript'=>'Weather Sunset','type'=>'1'),
'254'=> array('name'=>'l-weather-taurus', 'descript'=>'Weather Taurus','type'=>'1'),
'255'=> array('name'=>'l-weather-tempest', 'descript'=>'Weather Tempest','type'=>'1'),
'256'=> array('name'=>'l-weather-tempest-fullmoon', 'descript'=>'Weather Tempest Fullmoon','type'=>'1'),
'257'=> array('name'=>'l-weather-tempest-halfmoon', 'descript'=>'Weather Tempest Halfmoon','type'=>'1'),
'258'=> array('name'=>'l-weather-tempest-sun', 'descript'=>'Weather Tempest Sun','type'=>'1'),
'259'=> array('name'=>'l-weather-variable-fullmoon', 'descript'=>'Weather Variable Fullmoon','type'=>'1'),
'260'=> array('name'=>'l-weather-variable-halfmoon', 'descript'=>'Weather Variable Halfmoon','type'=>'1'),
'261'=> array('name'=>'l-weather-variable-sun', 'descript'=>'Weather Variable Sun','type'=>'1'),
'262'=> array('name'=>'l-weather-virgo', 'descript'=>'Weather Virgo','type'=>'1'),
'263'=> array('name'=>'l-weather-waning-cresent', 'descript'=>'Weather Waning Cresent','type'=>'1'),
'264'=> array('name'=>'l-weather-waning-gibbous', 'descript'=>'Weather Waning Gibbous','type'=>'1'),
'265'=> array('name'=>'l-weather-waxing-cresent', 'descript'=>'Weather Waxing Cresent','type'=>'1'),
'266'=> array('name'=>'l-weather-waxing-gibbous', 'descript'=>'Weather Waxing Gibbous','type'=>'1'),
'267'=> array('name'=>'l-weather-wind', 'descript'=>'Weather Wind','type'=>'1'),
'268'=> array('name'=>'l-weather-wind-e', 'descript'=>'Weather Wind E','type'=>'1'),
'269'=> array('name'=>'l-weather-wind-fullmoon', 'descript'=>'Weather Wind Fullmoon','type'=>'1'),
'270'=> array('name'=>'l-weather-wind-halfmoon', 'descript'=>'Weather Wind Halfmoon','type'=>'1'),
'271'=> array('name'=>'l-weather-wind-n', 'descript'=>'Weather Wind N','type'=>'1'),
'272'=> array('name'=>'l-weather-wind-ne', 'descript'=>'Weather Wind Ne','type'=>'1'),
'273'=> array('name'=>'l-weather-wind-nw', 'descript'=>'Weather Wind Nw','type'=>'1'),
'274'=> array('name'=>'l-weather-wind-s', 'descript'=>'Weather Wind S','type'=>'1'),
'275'=> array('name'=>'l-weather-wind-se', 'descript'=>'Weather Wind Se','type'=>'1'),
'276'=> array('name'=>'l-weather-wind-sun', 'descript'=>'Weather Wind Sun','type'=>'1'),
'277'=> array('name'=>'l-weather-wind-sw', 'descript'=>'Weather Wind Sw','type'=>'1'),
'278'=> array('name'=>'l-weather-wind-w', 'descript'=>'Weather Wind W','type'=>'1'),
'279'=> array('name'=>'l-weather-windgust', 'descript'=>'Weather Windgust','type'=>'1'),
'280'=> array('name'=>'l-software-add-vectorpoint', 'descript'=>'Software Add Vectorpoint','type'=>'1'),
'281'=> array('name'=>'l-software-box-oval', 'descript'=>'Software Box Oval','type'=>'1'),
'282'=> array('name'=>'l-software-box-polygon', 'descript'=>'Software Box Polygon','type'=>'1'),
'283'=> array('name'=>'l-software-box-rectangle', 'descript'=>'Software Box Rectangle','type'=>'1'),
'284'=> array('name'=>'l-software-box-roundedrectangle', 'descript'=>'Software Box Roundedrectangle','type'=>'1'),
'285'=> array('name'=>'l-software-character', 'descript'=>'Software Character','type'=>'1'),
'286'=> array('name'=>'l-software-crop', 'descript'=>'Software Crop','type'=>'1'),
'287'=> array('name'=>'l-software-eyedropper', 'descript'=>'Software Eyedropper','type'=>'1'),
'288'=> array('name'=>'l-software-font-allcaps', 'descript'=>'Software Font Allcaps','type'=>'1'),
'289'=> array('name'=>'l-software-font-baseline-shift', 'descript'=>'Software Font Baseline Shift','type'=>'1'),
'290'=> array('name'=>'l-software-font-horizontal-scale', 'descript'=>'Software Font Horizontal Scale','type'=>'1'),
'291'=> array('name'=>'l-software-font-kerning', 'descript'=>'Software Font Kerning','type'=>'1'),
'292'=> array('name'=>'l-software-font-leading', 'descript'=>'Software Font Leading','type'=>'1'),
'293'=> array('name'=>'l-software-font-size', 'descript'=>'Software Font Size','type'=>'1'),
'294'=> array('name'=>'l-software-font-smallcapital', 'descript'=>'Software Font Smallcapital','type'=>'1'),
'295'=> array('name'=>'l-software-font-smallcaps', 'descript'=>'Software Font Smallcaps','type'=>'1'),
'296'=> array('name'=>'l-software-font-strikethrough', 'descript'=>'Software Font Strikethrough','type'=>'1'),
'297'=> array('name'=>'l-software-font-tracking', 'descript'=>'Software Font Tracking','type'=>'1'),
'298'=> array('name'=>'l-software-font-underline', 'descript'=>'Software Font Underline','type'=>'1'),
'299'=> array('name'=>'l-software-font-vertical-scale', 'descript'=>'Software Font Vertical Scale','type'=>'1'),
'300'=> array('name'=>'l-software-horizontal-align-center', 'descript'=>'Software Horizontal Align Center','type'=>'1'),
'301'=> array('name'=>'l-software-horizontal-align-left', 'descript'=>'Software Horizontal Align Left','type'=>'1'),
'302'=> array('name'=>'l-software-horizontal-align-right', 'descript'=>'Software Horizontal Align Right','type'=>'1'),
'303'=> array('name'=>'l-software-horizontal-distribute-center', 'descript'=>'Software Horizontal Distribute Center','type'=>'1'),
'304'=> array('name'=>'l-software-horizontal-distribute-left', 'descript'=>'Software Horizontal Distribute Left','type'=>'1'),
'305'=> array('name'=>'l-software-horizontal-distribute-right', 'descript'=>'Software Horizontal Distribute Right','type'=>'1'),
'306'=> array('name'=>'l-software-indent-firstline', 'descript'=>'Software Indent Firstline','type'=>'1'),
'307'=> array('name'=>'l-software-indent-left', 'descript'=>'Software Indent Left','type'=>'1'),
'308'=> array('name'=>'l-software-indent-right', 'descript'=>'Software Indent Right','type'=>'1'),
'309'=> array('name'=>'l-software-lasso', 'descript'=>'Software Lasso','type'=>'1'),
'310'=> array('name'=>'l-software-layers1', 'descript'=>'Software Layers1','type'=>'1'),
'311'=> array('name'=>'l-software-layers2', 'descript'=>'Software Layers2','type'=>'1'),
'312'=> array('name'=>'l-software-layout', 'descript'=>'Software Layout','type'=>'1'),
'313'=> array('name'=>'l-software-layout-2columns', 'descript'=>'Software Layout 2Columns','type'=>'1'),
'314'=> array('name'=>'l-software-layout-3columns', 'descript'=>'Software Layout 3Columns','type'=>'1'),
'315'=> array('name'=>'l-software-layout-4columns', 'descript'=>'Software Layout 4Columns','type'=>'1'),
'316'=> array('name'=>'l-software-layout-4columns', 'descript'=>'Software Layout 4Columns','type'=>'1'),
'317'=> array('name'=>'l-software-layout-4lines', 'descript'=>'Software Layout 4Lines','type'=>'1'),
'318'=> array('name'=>'l-software-layout-8boxes', 'descript'=>'Software Layout 8Boxes','type'=>'1'),
'319'=> array('name'=>'l-software-layout-header', 'descript'=>'Software Layout Header','type'=>'1'),
'320'=> array('name'=>'l-software-layout-header-2columns', 'descript'=>'Software Layout Header 2Columns','type'=>'1'),
'321'=> array('name'=>'l-software-layout-header-3columns', 'descript'=>'Software Layout Header 3Columns','type'=>'1'),
'322'=> array('name'=>'l-software-layout-header-4boxes', 'descript'=>'Software Layout Header 4Boxes','type'=>'1'),
'323'=> array('name'=>'l-software-layout-header-4columns', 'descript'=>'Software Layout Header 4Columns','type'=>'1'),
'324'=> array('name'=>'l-software-layout-header-complex', 'descript'=>'Software Layout Header Complex','type'=>'1'),
'325'=> array('name'=>'l-software-layout-header-complex2', 'descript'=>'Software Layout Header Complex2','type'=>'1'),
'326'=> array('name'=>'l-software-layout-header-complex3', 'descript'=>'Software Layout Header Complex3','type'=>'1'),
'327'=> array('name'=>'l-software-layout-header-complex4', 'descript'=>'Software Layout Header Complex4','type'=>'1'),
'328'=> array('name'=>'l-software-layout-header-sideleft', 'descript'=>'Software Layout Header Sideleft','type'=>'1'),
'329'=> array('name'=>'l-software-layout-header-sideright', 'descript'=>'Software Layout Header Sideright','type'=>'1'),
'330'=> array('name'=>'l-software-layout-sidebar-left', 'descript'=>'Software Layout Sidebar Left','type'=>'1'),
'331'=> array('name'=>'l-software-layout-sidebar-right', 'descript'=>'Software Layout Sidebar Right','type'=>'1'),
'332'=> array('name'=>'l-software-magnete', 'descript'=>'Software Magnete','type'=>'1'),
'333'=> array('name'=>'l-software-pages', 'descript'=>'Software Pages','type'=>'1'),
'334'=> array('name'=>'l-software-paintbrush', 'descript'=>'Software Paintbrush','type'=>'1'),
'335'=> array('name'=>'l-software-paintbucket', 'descript'=>'Software Paintbucket','type'=>'1'),
'336'=> array('name'=>'l-software-paintroller', 'descript'=>'Software Paintroller','type'=>'1'),
'337'=> array('name'=>'l-software-paragraph', 'descript'=>'Software Paragraph','type'=>'1'),
'338'=> array('name'=>'l-software-paragraph-align-left', 'descript'=>'Software Paragraph Align Left','type'=>'1'),
'339'=> array('name'=>'l-software-paragraph-align-right', 'descript'=>'Software Paragraph Align Right','type'=>'1'),
'340'=> array('name'=>'l-software-paragraph-center', 'descript'=>'Software Paragraph Center','type'=>'1'),
'341'=> array('name'=>'l-software-paragraph-justify-all', 'descript'=>'Software Paragraph Justify All','type'=>'1'),
'342'=> array('name'=>'l-software-paragraph-justify-center', 'descript'=>'Software Paragraph Justify Center','type'=>'1'),
'343'=> array('name'=>'l-software-paragraph-justify-left', 'descript'=>'Software Paragraph Justify Left','type'=>'1'),
'344'=> array('name'=>'l-software-paragraph-justify-right', 'descript'=>'Software Paragraph Justify Right','type'=>'1'),
'345'=> array('name'=>'l-software-paragraph-space-after', 'descript'=>'Software Paragraph Space After','type'=>'1'),
'346'=> array('name'=>'l-software-paragraph-space-before', 'descript'=>'Software Paragraph Space Before','type'=>'1'),
'347'=> array('name'=>'l-software-pathfinder-exclude', 'descript'=>'Software Pathfinder Exclude','type'=>'1'),
'348'=> array('name'=>'l-software-pathfinder-intersect', 'descript'=>'Software Pathfinder Intersect','type'=>'1'),
'349'=> array('name'=>'l-software-pathfinder-subtract', 'descript'=>'Software Pathfinder Subtract','type'=>'1'),
'350'=> array('name'=>'l-software-pathfinder-unite', 'descript'=>'Software Pathfinder Unite','type'=>'1'),
'351'=> array('name'=>'l-software-pen', 'descript'=>'Software Pen','type'=>'1'),
'352'=> array('name'=>'l-software-pen-add', 'descript'=>'Software Pen Add','type'=>'1'),
'353'=> array('name'=>'l-software-pen-remove', 'descript'=>'Software Pen Remove','type'=>'1'),
'354'=> array('name'=>'l-software-pencil', 'descript'=>'Software Pencil','type'=>'1'),
'355'=> array('name'=>'l-software-polygonallasso', 'descript'=>'Software Polygonallasso','type'=>'1'),
'356'=> array('name'=>'l-software-reflect-horizontal', 'descript'=>'Software Reflect Horizontal','type'=>'1'),
'357'=> array('name'=>'l-software-reflect-vertical', 'descript'=>'Software Reflect Vertical','type'=>'1'),
'358'=> array('name'=>'l-software-remove-vectorpoint', 'descript'=>'Software Remove Vectorpoint','type'=>'1'),
'359'=> array('name'=>'l-software-scale-expand', 'descript'=>'Software Scale Expand','type'=>'1'),
'360'=> array('name'=>'l-software-scale-reduce', 'descript'=>'Software Scale Reduce','type'=>'1'),
'361'=> array('name'=>'l-software-selection-oval', 'descript'=>'Software Selection Oval','type'=>'1'),
'362'=> array('name'=>'l-software-selection-polygon', 'descript'=>'Software Selection Polygon','type'=>'1'),
'363'=> array('name'=>'l-software-selection-rectangle', 'descript'=>'Software Selection Rectangle','type'=>'1'),
'364'=> array('name'=>'l-software-selection-roundedrectangle', 'descript'=>'Software Selection Roundedrectangle','type'=>'1'),
'365'=> array('name'=>'l-software-shape-oval', 'descript'=>'Software Shape Oval','type'=>'1'),
'366'=> array('name'=>'l-software-shape-polygon', 'descript'=>'Software Shape Polygon','type'=>'1'),
'367'=> array('name'=>'l-software-shape-rectangle', 'descript'=>'Software Shape Rectangle','type'=>'1'),
'368'=> array('name'=>'l-software-shape-roundedrectangle', 'descript'=>'Software Shape Roundedrectangle','type'=>'1'),
'369'=> array('name'=>'l-software-slice', 'descript'=>'Software Slice','type'=>'1'),
'370'=> array('name'=>'l-software-transform-bezier', 'descript'=>'Software Transform Bezier','type'=>'1'),
'371'=> array('name'=>'l-software-vector-box', 'descript'=>'Software Vector Box','type'=>'1'),
'372'=> array('name'=>'l-software-vector-composite', 'descript'=>'Software Vector Composite','type'=>'1'),
'373'=> array('name'=>'l-software-vector-line', 'descript'=>'Software Vector Line','type'=>'1'),
'374'=> array('name'=>'l-software-vertical-align-bottom', 'descript'=>'Software Vertical Align Bottom','type'=>'1'),
'375'=> array('name'=>'l-software-vertical-align-center', 'descript'=>'Software Vertical Align Center','type'=>'1'),
'376'=> array('name'=>'l-software-vertical-align-top', 'descript'=>'Software Vertical Align Top','type'=>'1'),
'377'=> array('name'=>'l-software-vertical-distribute-bottom', 'descript'=>'Software Vertical Distribute Bottom','type'=>'1'),
'378'=> array('name'=>'l-software-vertical-distribute-center', 'descript'=>'Software Vertical Distribute Center','type'=>'1'),
'379'=> array('name'=>'l-software-vertical-distribute-top', 'descript'=>'Software Vertical Distribute Top','type'=>'1'),
'380'=> array('name'=>'l-music-beginning-button', 'descript'=>'Music Beginning Button','type'=>'1'),
'381'=> array('name'=>'l-music-bell', 'descript'=>'Music Bell','type'=>'1'),
'382'=> array('name'=>'l-music-cd', 'descript'=>'Music Cd','type'=>'1'),
'383'=> array('name'=>'l-music-diapason', 'descript'=>'Music Diapason','type'=>'1'),
'384'=> array('name'=>'l-music-eject-button', 'descript'=>'Music Eject Button','type'=>'1'),
'385'=> array('name'=>'l-music-end-button', 'descript'=>'Music End Button','type'=>'1'),
'386'=> array('name'=>'l-music-fastforward-button', 'descript'=>'Music Fastforward Button','type'=>'1'),
'387'=> array('name'=>'l-music-headphones', 'descript'=>'Music Headphones','type'=>'1'),
'388'=> array('name'=>'l-music-ipod', 'descript'=>'Music Ipod','type'=>'1'),
'389'=> array('name'=>'l-music-loudspeaker', 'descript'=>'Music Loudspeaker','type'=>'1'),
'390'=> array('name'=>'l-music-microphone', 'descript'=>'Music Microphone','type'=>'1'),
'391'=> array('name'=>'l-music-microphone-old', 'descript'=>'Music Microphone Old','type'=>'1'),
'392'=> array('name'=>'l-music-mixer', 'descript'=>'Music Mixer','type'=>'1'),
'393'=> array('name'=>'l-music-mute', 'descript'=>'Music Mute','type'=>'1'),
'394'=> array('name'=>'l-music-note-multiple', 'descript'=>'Music Note Multiple','type'=>'1'),
'395'=> array('name'=>'l-music-note-single', 'descript'=>'Music Note Single','type'=>'1'),
'396'=> array('name'=>'l-music-pause-button', 'descript'=>'Music Pause Button','type'=>'1'),
'397'=> array('name'=>'l-music-play-button', 'descript'=>'Music Play Button','type'=>'1'),
'398'=> array('name'=>'l-music-playlist', 'descript'=>'Music Playlist','type'=>'1'),
'399'=> array('name'=>'l-music-radio-ghettoblaster', 'descript'=>'Music Radio Ghettoblaster','type'=>'1'),
'400'=> array('name'=>'l-music-radio-portable', 'descript'=>'Music Radio Portable','type'=>'1'),
'401'=> array('name'=>'l-music-record', 'descript'=>'Music Record','type'=>'1'),
'402'=> array('name'=>'l-music-recordplayer', 'descript'=>'Music Recordplayer','type'=>'1'),
'403'=> array('name'=>'l-music-repeat-button', 'descript'=>'Music Repeat Button','type'=>'1'),
'404'=> array('name'=>'l-music-rewind-button', 'descript'=>'Music Rewind Button','type'=>'1'),
'405'=> array('name'=>'l-music-shuffle-button', 'descript'=>'Music Shuffle Button','type'=>'1'),
'406'=> array('name'=>'l-music-stop-button', 'descript'=>'Music Stop Button','type'=>'1'),
'407'=> array('name'=>'l-music-tape', 'descript'=>'Music Tape','type'=>'1'),
'408'=> array('name'=>'l-music-volume-down', 'descript'=>'Music Volume Down','type'=>'1'),
'409'=> array('name'=>'l-music-volume-up', 'descript'=>'Music Volume Up','type'=>'1'),
'410'=> array('name'=>'l-ecommerce-bag', 'descript'=>'Ecommerce Bag','type'=>'1'),
'411'=> array('name'=>'l-ecommerce-bag-check', 'descript'=>'Ecommerce Bag Check','type'=>'1'),
'412'=> array('name'=>'l-ecommerce-bag-cloud', 'descript'=>'Ecommerce Bag Cloud','type'=>'1'),
'413'=> array('name'=>'l-ecommerce-bag-download', 'descript'=>'Ecommerce Bag Download','type'=>'1'),
'414'=> array('name'=>'l-ecommerce-bag-minus', 'descript'=>'Ecommerce Bag Minus','type'=>'1'),
'415'=> array('name'=>'l-ecommerce-bag-plus', 'descript'=>'Ecommerce Bag Plus','type'=>'1'),
'416'=> array('name'=>'l-ecommerce-bag-refresh', 'descript'=>'Ecommerce Bag Refresh','type'=>'1'),
'417'=> array('name'=>'l-ecommerce-bag-remove', 'descript'=>'Ecommerce Bag Remove','type'=>'1'),
'418'=> array('name'=>'l-ecommerce-bag-search', 'descript'=>'Ecommerce Bag Search','type'=>'1'),
'419'=> array('name'=>'l-ecommerce-bag-upload', 'descript'=>'Ecommerce Bag Upload','type'=>'1'),
'420'=> array('name'=>'l-ecommerce-banknote', 'descript'=>'Ecommerce Banknote','type'=>'1'),
'421'=> array('name'=>'l-ecommerce-banknotes', 'descript'=>'Ecommerce Banknotes','type'=>'1'),
'422'=> array('name'=>'l-ecommerce-basket', 'descript'=>'Ecommerce Basket','type'=>'1'),
'423'=> array('name'=>'l-ecommerce-basket-check', 'descript'=>'Ecommerce Basket Check','type'=>'1'),
'424'=> array('name'=>'l-ecommerce-basket-cloud', 'descript'=>'Ecommerce Basket Cloud','type'=>'1'),
'425'=> array('name'=>'l-ecommerce-basket-download', 'descript'=>'Ecommerce Basket Download','type'=>'1'),
'426'=> array('name'=>'l-ecommerce-basket-minus', 'descript'=>'Ecommerce Basket Minus','type'=>'1'),
'427'=> array('name'=>'l-ecommerce-basket-plus', 'descript'=>'Ecommerce Basket Plus','type'=>'1'),
'428'=> array('name'=>'l-ecommerce-basket-refresh', 'descript'=>'Ecommerce Basket Refresh','type'=>'1'),
'429'=> array('name'=>'l-ecommerce-basket-remove', 'descript'=>'Ecommerce Basket Remove','type'=>'1'),
'430'=> array('name'=>'l-ecommerce-basket-search', 'descript'=>'Ecommerce Basket Search','type'=>'1'),
'431'=> array('name'=>'l-ecommerce-basket-upload', 'descript'=>'Ecommerce Basket Upload','type'=>'1'),
'432'=> array('name'=>'l-ecommerce-bath', 'descript'=>'Ecommerce Bath','type'=>'1'),
'433'=> array('name'=>'l-ecommerce-cart', 'descript'=>'Ecommerce Cart','type'=>'1'),
'434'=> array('name'=>'l-ecommerce-cart-check', 'descript'=>'Ecommerce Cart Check','type'=>'1'),
'435'=> array('name'=>'l-ecommerce-cart-cloud', 'descript'=>'Ecommerce Cart Cloud','type'=>'1'),
'436'=> array('name'=>'l-ecommerce-cart-content', 'descript'=>'Ecommerce Cart Content','type'=>'1'),
'437'=> array('name'=>'l-ecommerce-cart-download', 'descript'=>'Ecommerce Cart Download','type'=>'1'),
'438'=> array('name'=>'l-ecommerce-cart-minus', 'descript'=>'Ecommerce Cart Minus','type'=>'1'),
'439'=> array('name'=>'l-ecommerce-cart-plus', 'descript'=>'Ecommerce Cart Plus','type'=>'1'),
'440'=> array('name'=>'l-ecommerce-cart-refresh', 'descript'=>'Ecommerce Cart Refresh','type'=>'1'),
'441'=> array('name'=>'l-ecommerce-cart-remove', 'descript'=>'Ecommerce Cart Remove','type'=>'1'),
'442'=> array('name'=>'l-ecommerce-cart-search', 'descript'=>'Ecommerce Cart Search','type'=>'1'),
'443'=> array('name'=>'l-ecommerce-cart-upload', 'descript'=>'Ecommerce Cart Upload','type'=>'1'),
'444'=> array('name'=>'l-ecommerce-cent', 'descript'=>'Ecommerce Cent','type'=>'1'),
'445'=> array('name'=>'l-ecommerce-colon', 'descript'=>'Ecommerce Colon','type'=>'1'),
'446'=> array('name'=>'l-ecommerce-creditcard', 'descript'=>'Ecommerce Creditcard','type'=>'1'),
'447'=> array('name'=>'l-ecommerce-diamond', 'descript'=>'Ecommerce Diamond','type'=>'1'),
'448'=> array('name'=>'l-ecommerce-dollar', 'descript'=>'Ecommerce Dollar','type'=>'1'),
'449'=> array('name'=>'l-ecommerce-euro', 'descript'=>'Ecommerce Euro','type'=>'1'),
'450'=> array('name'=>'l-ecommerce-franc', 'descript'=>'Ecommerce Franc','type'=>'1'),
'451'=> array('name'=>'l-ecommerce-gift', 'descript'=>'Ecommerce Gift','type'=>'1'),
'452'=> array('name'=>'l-ecommerce-graph1', 'descript'=>'Ecommerce Graph1','type'=>'1'),
'453'=> array('name'=>'l-ecommerce-graph2', 'descript'=>'Ecommerce Graph2','type'=>'1'),
'454'=> array('name'=>'l-ecommerce-graph3', 'descript'=>'Ecommerce Graph3','type'=>'1'),
'455'=> array('name'=>'l-ecommerce-graph-decrease', 'descript'=>'Ecommerce Graph Decrease','type'=>'1'),
'456'=> array('name'=>'l-ecommerce-graph-increase', 'descript'=>'Ecommerce Graph Increase','type'=>'1'),
'457'=> array('name'=>'l-ecommerce-guarani', 'descript'=>'Ecommerce Guarani','type'=>'1'),
'458'=> array('name'=>'l-ecommerce-kips', 'descript'=>'Ecommerce Kips','type'=>'1'),
'459'=> array('name'=>'l-ecommerce-lira', 'descript'=>'Ecommerce Lira','type'=>'1'),
'460'=> array('name'=>'l-ecommerce-megaphone', 'descript'=>'Ecommerce Megaphone','type'=>'1'),
'461'=> array('name'=>'l-ecommerce-money', 'descript'=>'Ecommerce Money','type'=>'1'),
'462'=> array('name'=>'l-ecommerce-naira', 'descript'=>'Ecommerce Naira','type'=>'1'),
'463'=> array('name'=>'l-ecommerce-pesos', 'descript'=>'Ecommerce Pesos','type'=>'1'),
'464'=> array('name'=>'l-ecommerce-pound', 'descript'=>'Ecommerce Pound','type'=>'1'),
'465'=> array('name'=>'l-ecommerce-receipt', 'descript'=>'Ecommerce Receipt','type'=>'1'),
'466'=> array('name'=>'l-ecommerce-receipt-bath', 'descript'=>'Ecommerce Receipt Bath','type'=>'1'),
'467'=> array('name'=>'l-ecommerce-receipt-cent', 'descript'=>'Ecommerce Receipt Cent','type'=>'1'),
'468'=> array('name'=>'l-ecommerce-receipt-dollar', 'descript'=>'Ecommerce Receipt Dollar','type'=>'1'),
'469'=> array('name'=>'l-ecommerce-receipt-euro', 'descript'=>'Ecommerce Receipt Euro','type'=>'1'),
'470'=> array('name'=>'l-ecommerce-receipt-franc', 'descript'=>'Ecommerce Receipt Franc','type'=>'1'),
'471'=> array('name'=>'l-ecommerce-receipt-guarani', 'descript'=>'Ecommerce Receipt Guarani','type'=>'1'),
'472'=> array('name'=>'l-ecommerce-receipt-kips', 'descript'=>'Ecommerce Receipt Kips','type'=>'1'),
'473'=> array('name'=>'l-ecommerce-receipt-lira', 'descript'=>'Ecommerce Receipt Lira','type'=>'1'),
'474'=> array('name'=>'l-ecommerce-receipt-naira', 'descript'=>'Ecommerce Receipt Naira','type'=>'1'),
'475'=> array('name'=>'l-ecommerce-receipt-pesos', 'descript'=>'Ecommerce Receipt Pesos','type'=>'1'),
'476'=> array('name'=>'l-ecommerce-receipt-pound', 'descript'=>'Ecommerce Receipt Pound','type'=>'1'),
'477'=> array('name'=>'l-ecommerce-receipt-rublo', 'descript'=>'Ecommerce Receipt Rublo','type'=>'1'),
'478'=> array('name'=>'l-ecommerce-receipt-rupee', 'descript'=>'Ecommerce Receipt Rupee','type'=>'1'),
'479'=> array('name'=>'l-ecommerce-receipt-tugrik', 'descript'=>'Ecommerce Receipt Tugrik','type'=>'1'),
'480'=> array('name'=>'l-ecommerce-receipt-won', 'descript'=>'Ecommerce Receipt Won','type'=>'1'),
'481'=> array('name'=>'l-ecommerce-receipt-yen', 'descript'=>'Ecommerce Receipt Yen','type'=>'1'),
'482'=> array('name'=>'l-ecommerce-receipt-yen2', 'descript'=>'Ecommerce Receipt Yen2','type'=>'1'),
'483'=> array('name'=>'l-ecommerce-recept-colon', 'descript'=>'Ecommerce Recept Colon','type'=>'1'),
'484'=> array('name'=>'l-ecommerce-rublo', 'descript'=>'Ecommerce Rublo','type'=>'1'),
'485'=> array('name'=>'l-ecommerce-rupee', 'descript'=>'Ecommerce Rupee','type'=>'1'),
'486'=> array('name'=>'l-ecommerce-safe', 'descript'=>'Ecommerce Safe','type'=>'1'),
'487'=> array('name'=>'l-ecommerce-sale', 'descript'=>'Ecommerce Sale','type'=>'1'),
'488'=> array('name'=>'l-ecommerce-sales', 'descript'=>'Ecommerce Sales','type'=>'1'),
'489'=> array('name'=>'l-ecommerce-ticket', 'descript'=>'Ecommerce Ticket','type'=>'1'),
'490'=> array('name'=>'l-ecommerce-tugriks', 'descript'=>'Ecommerce Tugriks','type'=>'1'),
'491'=> array('name'=>'l-ecommerce-wallet', 'descript'=>'Ecommerce Wallet','type'=>'1'),
'492'=> array('name'=>'l-ecommerce-won', 'descript'=>'Ecommerce Won','type'=>'1'),
'493'=> array('name'=>'l-ecommerce-yen', 'descript'=>'Ecommerce Yen','type'=>'1'),
'494'=> array('name'=>'l-ecommerce-yen2', 'descript'=>'Ecommerce Yen2','type'=>'1'),
'495'=> array('name'=>'l-arrows-anticlockwise', 'descript'=>'Arrows Anticlockwise','type'=>'1'),
'496'=> array('name'=>'l-arrows-anticlockwise-dashed', 'descript'=>'Arrows Anticlockwise Dashed','type'=>'1'),
'497'=> array('name'=>'l-arrows-button-down', 'descript'=>'Arrows Button Down','type'=>'1'),
'498'=> array('name'=>'l-arrows-button-off', 'descript'=>'Arrows Button Off','type'=>'1'),
'499'=> array('name'=>'l-arrows-button-on', 'descript'=>'Arrows Button On','type'=>'1'),
'500'=> array('name'=>'l-arrows-button-up', 'descript'=>'Arrows Button Up','type'=>'1'),
'501'=> array('name'=>'l-arrows-check', 'descript'=>'Arrows Check','type'=>'1'),
'502'=> array('name'=>'l-arrows-circle-check', 'descript'=>'Arrows Circle Check','type'=>'1'),
'503'=> array('name'=>'l-arrows-circle-down', 'descript'=>'Arrows Circle Down','type'=>'1'),
'504'=> array('name'=>'l-arrows-circle-downleft', 'descript'=>'Arrows Circle Downleft','type'=>'1'),
'505'=> array('name'=>'l-arrows-circle-downright', 'descript'=>'Arrows Circle Downright','type'=>'1'),
'506'=> array('name'=>'l-arrows-circle-left', 'descript'=>'Arrows Circle Left','type'=>'1'),
'507'=> array('name'=>'l-arrows-circle-minus', 'descript'=>'Arrows Circle Minus','type'=>'1'),
'508'=> array('name'=>'l-arrows-circle-plus', 'descript'=>'Arrows Circle Plus','type'=>'1'),
'509'=> array('name'=>'l-arrows-circle-remove', 'descript'=>'Arrows Circle Remove','type'=>'1'),
'510'=> array('name'=>'l-arrows-circle-right', 'descript'=>'Arrows Circle Right','type'=>'1'),
'511'=> array('name'=>'l-arrows-circle-up', 'descript'=>'Arrows Circle Up','type'=>'1'),
'512'=> array('name'=>'l-arrows-circle-upleft', 'descript'=>'Arrows Circle Upleft','type'=>'1'),
'513'=> array('name'=>'l-arrows-circle-upright', 'descript'=>'Arrows Circle Upright','type'=>'1'),
'514'=> array('name'=>'l-arrows-clockwise', 'descript'=>'Arrows Clockwise','type'=>'1'),
'515'=> array('name'=>'l-arrows-clockwise-dashed', 'descript'=>'Arrows Clockwise Dashed','type'=>'1'),
'516'=> array('name'=>'l-arrows-compress', 'descript'=>'Arrows Compress','type'=>'1'),
'517'=> array('name'=>'l-arrows-deny', 'descript'=>'Arrows Deny','type'=>'1'),
'518'=> array('name'=>'l-arrows-diagonal', 'descript'=>'Arrows Diagonal','type'=>'1'),
'519'=> array('name'=>'l-arrows-diagonal2', 'descript'=>'Arrows Diagonal2','type'=>'1'),
'520'=> array('name'=>'l-arrows-down', 'descript'=>'Arrows Down','type'=>'1'),
'521'=> array('name'=>'l-arrows-down-double-34', 'descript'=>'Arrows Down Double 34','type'=>'1'),
'522'=> array('name'=>'l-arrows-downleft', 'descript'=>'Arrows Downleft','type'=>'1'),
'523'=> array('name'=>'l-arrows-downright', 'descript'=>'Arrows Downright','type'=>'1'),
'524'=> array('name'=>'l-arrows-drag-down', 'descript'=>'Arrows Drag Down','type'=>'1'),
'525'=> array('name'=>'l-arrows-drag-down-dashed', 'descript'=>'Arrows Drag Down Dashed','type'=>'1'),
'526'=> array('name'=>'l-arrows-drag-horiz', 'descript'=>'Arrows Drag Horiz','type'=>'1'),
'527'=> array('name'=>'l-arrows-drag-left', 'descript'=>'Arrows Drag Left','type'=>'1'),
'528'=> array('name'=>'l-arrows-drag-left-dashed', 'descript'=>'Arrows Drag Left Dashed','type'=>'1'),
'529'=> array('name'=>'l-arrows-drag-right', 'descript'=>'Arrows Drag Right','type'=>'1'),
'530'=> array('name'=>'l-arrows-drag-right-dashed', 'descript'=>'Arrows Drag Right Dashed','type'=>'1'),
'531'=> array('name'=>'l-arrows-drag-up', 'descript'=>'Arrows Drag Up','type'=>'1'),
'532'=> array('name'=>'l-arrows-drag-up-dashed', 'descript'=>'Arrows Drag Up Dashed','type'=>'1'),
'533'=> array('name'=>'l-arrows-drag-vert', 'descript'=>'Arrows Drag Vert','type'=>'1'),
'534'=> array('name'=>'l-arrows-exclamation', 'descript'=>'Arrows Exclamation','type'=>'1'),
'535'=> array('name'=>'l-arrows-expand', 'descript'=>'Arrows Expand','type'=>'1'),
'536'=> array('name'=>'l-arrows-expand-diagonal1', 'descript'=>'Arrows Expand Diagonal1','type'=>'1'),
'537'=> array('name'=>'l-arrows-expand-horizontal1', 'descript'=>'Arrows Expand Horizontal1','type'=>'1'),
'538'=> array('name'=>'l-arrows-expand-vertical1', 'descript'=>'Arrows Expand Vertical1','type'=>'1'),
'539'=> array('name'=>'l-arrows-fit-horizontal', 'descript'=>'Arrows Fit Horizontal','type'=>'1'),
'540'=> array('name'=>'l-arrows-fit-vertical', 'descript'=>'Arrows Fit Vertical','type'=>'1'),
'541'=> array('name'=>'l-arrows-glide', 'descript'=>'Arrows Glide','type'=>'1'),
'542'=> array('name'=>'l-arrows-glide-horizontal', 'descript'=>'Arrows Glide Horizontal','type'=>'1'),
'543'=> array('name'=>'l-arrows-glide-vertical', 'descript'=>'Arrows Glide Vertical','type'=>'1'),
'544'=> array('name'=>'l-arrows-hamburger1', 'descript'=>'Arrows Hamburger1','type'=>'1'),
'545'=> array('name'=>'l-arrows-hamburger-2', 'descript'=>'Arrows Hamburger 2','type'=>'1'),
'546'=> array('name'=>'l-arrows-horizontal', 'descript'=>'Arrows Horizontal','type'=>'1'),
'547'=> array('name'=>'l-arrows-info', 'descript'=>'Arrows Info','type'=>'1'),
'548'=> array('name'=>'l-arrows-keyboard-alt', 'descript'=>'Arrows Keyboard Alt','type'=>'1'),
'549'=> array('name'=>'l-arrows-keyboard-cmd-29', 'descript'=>'Arrows Keyboard Cmd 29','type'=>'1'),
'550'=> array('name'=>'l-arrows-keyboard-delete', 'descript'=>'Arrows Keyboard Delete','type'=>'1'),
'551'=> array('name'=>'l-arrows-keyboard-down-28', 'descript'=>'Arrows Keyboard Down 28','type'=>'1'),
'552'=> array('name'=>'l-arrows-keyboard-left', 'descript'=>'Arrows Keyboard Left','type'=>'1'),
'553'=> array('name'=>'l-arrows-keyboard-return', 'descript'=>'Arrows Keyboard Return','type'=>'1'),
'554'=> array('name'=>'l-arrows-keyboard-right', 'descript'=>'Arrows Keyboard Right','type'=>'1'),
'555'=> array('name'=>'l-arrows-keyboard-shift', 'descript'=>'Arrows Keyboard Shift','type'=>'1'),
'556'=> array('name'=>'l-arrows-keyboard-tab', 'descript'=>'Arrows Keyboard Tab','type'=>'1'),
'557'=> array('name'=>'l-arrows-keyboard-up', 'descript'=>'Arrows Keyboard Up','type'=>'1'),
'558'=> array('name'=>'l-arrows-left', 'descript'=>'Arrows Left','type'=>'1'),
'559'=> array('name'=>'l-arrows-left-double-32', 'descript'=>'Arrows Left Double 32','type'=>'1'),
'560'=> array('name'=>'l-arrows-minus', 'descript'=>'Arrows Minus','type'=>'1'),
'561'=> array('name'=>'l-arrows-move', 'descript'=>'Arrows Move','type'=>'1'),
'562'=> array('name'=>'l-arrows-move2', 'descript'=>'Arrows Move2','type'=>'1'),
'563'=> array('name'=>'l-arrows-move-bottom', 'descript'=>'Arrows Move Bottom','type'=>'1'),
'564'=> array('name'=>'l-arrows-move-left', 'descript'=>'Arrows Move Left','type'=>'1'),
'565'=> array('name'=>'l-arrows-move-right', 'descript'=>'Arrows Move Right','type'=>'1'),
'566'=> array('name'=>'l-arrows-move-top', 'descript'=>'Arrows Move Top','type'=>'1'),
'567'=> array('name'=>'l-arrows-plus', 'descript'=>'Arrows Plus','type'=>'1'),
'568'=> array('name'=>'l-arrows-question', 'descript'=>'Arrows Question','type'=>'1'),
'569'=> array('name'=>'l-arrows-remove', 'descript'=>'Arrows Remove','type'=>'1'),
'570'=> array('name'=>'l-arrows-right', 'descript'=>'Arrows Right','type'=>'1'),
'571'=> array('name'=>'l-arrows-right-double-31', 'descript'=>'Arrows Right Double 31','type'=>'1'),
'572'=> array('name'=>'l-arrows-rotate', 'descript'=>'Arrows Rotate','type'=>'1'),
'573'=> array('name'=>'l-arrows-rotate-anti', 'descript'=>'Arrows Rotate Anti','type'=>'1'),
'574'=> array('name'=>'l-arrows-rotate-anti-dashed', 'descript'=>'Arrows Rotate Anti Dashed','type'=>'1'),
'575'=> array('name'=>'l-arrows-rotate-dashed', 'descript'=>'Arrows Rotate Dashed','type'=>'1'),
'576'=> array('name'=>'l-arrows-shrink', 'descript'=>'Arrows Shrink','type'=>'1'),
'577'=> array('name'=>'l-arrows-shrink-diagonal1', 'descript'=>'Arrows Shrink Diagonal1','type'=>'1'),
'578'=> array('name'=>'l-arrows-shrink-diagonal2', 'descript'=>'Arrows Shrink Diagonal2','type'=>'1'),
'579'=> array('name'=>'l-arrows-shrink-horizonal2', 'descript'=>'Arrows Shrink Horizonal2','type'=>'1'),
'580'=> array('name'=>'l-arrows-shrink-horizontal1', 'descript'=>'Arrows Shrink Horizontal1','type'=>'1'),
'581'=> array('name'=>'l-arrows-shrink-vertical1', 'descript'=>'Arrows Shrink Vertical1','type'=>'1'),
'582'=> array('name'=>'l-arrows-shrink-vertical2', 'descript'=>'Arrows Shrink Vertical2','type'=>'1')

);

print json_encode($imagenes);

?>